add_newline = false

[cmd_duration]
disabled = true

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[kubernetes]
disabled = false

[elixir]
disabled = true

[erlang]
disabled = true

[package]
disabled = true

[gcloud]
disabled = true

[golang]
disabled = false
